name: Angular CI

on:
  pull_request:
    branches:
      - main # Or your main development branch like 'develop' or 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use your project's Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run Angular tests
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless
